import requests

url = "http://localhost:8080/HearthstoneCLC/rest/cards/update"

payload = "{\r\n    \"cards\":\r\n    [\r\n        {\r\n            \"name\": \"Murloc Tidecaller\",\r\n            \"health\": 2,\r\n            \"manaCost\": 1\r\n        },\r\n        {\r\n            \"name\": \"Selfless Hero\",\r\n            \"health\": 1,\r\n            \"manaCost\": 1\r\n        },\r\n        {\r\n            \"name\": \"Unstable Ghoul\",\r\n            \"health\": 3,\r\n            \"manaCost\": 2\r\n        },\r\n        {\r\n            \"name\": \"Vulgar Homunculus\",\r\n            \"health\": 4,\r\n            \"manaCost\": 2\r\n        },\r\n        {\r\n            \"name\": \"Kaboom Bot\",\r\n            \"health\": 2,\r\n            \"manaCost\": 3\r\n        },\r\n        {\r\n            \"name\": \"Metaltooth Leaper\",\r\n            \"health\": 3,\r\n            \"manaCost\": 3\r\n        },\r\n        {\r\n            \"name\": \"Murloc Warleader\",\r\n            \"health\": 3,\r\n            \"manaCost\": 3\r\n        },\r\n        {\r\n            \"name\": \"Red Whelp\",\r\n            \"health\": 2,\r\n            \"manaCost\": 1\r\n        },\r\n        {\r\n            \"name\": \"Refreshing Anomaly\",\r\n            \"health\": 3,\r\n            \"manaCost\": 1\r\n        },\r\n        {\r\n            \"name\": \"Scallywag\",\r\n            \"health\": 1,\r\n            \"manaCost\": 1\r\n        },\r\n        {\r\n            \"name\": \"Shifter Zerus\",\r\n            \"health\": 1,\r\n            \"manaCost\": 1\r\n        },\r\n        {\r\n            \"name\": \"Dragonspawn Lieutenant\",\r\n            \"health\": 3,\r\n            \"manaCost\": 2\r\n        },\r\n        {\r\n            \"name\": \"Micro Machine\",\r\n            \"health\": 2,\r\n            \"manaCost\": 2\r\n        },\r\n        {\r\n            \"name\": \"Iron Sensei\",\r\n            \"health\": 2,\r\n            \"manaCost\": 3\r\n        },\r\n        {\r\n            \"name\": \"Imp Gang Boss\",\r\n            \"health\": 4,\r\n            \"manaCost\": 3\r\n        },\r\n        {\r\n            \"name\": \"Cave Hydra\",\r\n            \"health\": 4,\r\n            \"manaCost\": 3\r\n        },\r\n        {\r\n            \"name\": \"Micro Mummy\",\r\n            \"health\": 2,\r\n            \"manaCost\": 2\r\n        },\r\n        {\r\n            \"name\": \"Kindly Grandmother\",\r\n            \"health\": 1,\r\n            \"manaCost\": 2\r\n        },\r\n        {\r\n            \"name\": \"Khadgar\",\r\n            \"health\": 2,\r\n            \"manaCost\": 2\r\n        },\r\n        {\r\n            \"name\": \"Toxfin\",\r\n            \"health\": 1,\r\n            \"manaCost\": 1\r\n        },\r\n        {\r\n            \"name\": \"Alleycat\",\r\n            \"health\": 1,\r\n            \"manaCost\": 1\r\n        }\r\n    ]\r\n}"
headers = {
  'Content-Type': 'application/json'
}

response = requests.request("POST", url, headers=headers, data = payload)

print(response.text.encode('utf8'))
